### ISSUE TITLE
Add several executables

### ISSUE THREAD

**Issue by pjyork** [tatool/tatool-web#109]
I've developed a executables which I would like to host on Tatool-Web.
[MatrixReasoning.zip](https://github.com/tatool/tatool-web/files/1724614/MatrixReasoning.zip)
[NumberReasoning.zip](https://github.com/tatool/tatool-web/files/1724615/NumberReasoning.zip)
[Rotation3D.zip](https://github.com/tatool/tatool-web/files/1724616/Rotation3D.zip)
[VerbalReasoning.zip](https://github.com/tatool/tatool-web/files/1724617/VerbalReasoning.zip)
[AbstractReasoning.zip](https://github.com/tatool/tatool-web/files/1724618/AbstractReasoning.zip)
[FiguralAnalogies.zip](https://github.com/tatool/tatool-web/files/1724619/FiguralAnalogies.zip)

**Comment by alocher** [comment]
I will go through these on the weekend and let you know once they're available.

**Comment by Pete-York** [comment]
Hi,

A few of these are very similar, and I've though of a way of combining them into a single multiple-choice module with a paramater for number of options, and a parameter for whether the choices should be lettered or numbered. I'm gonna make this change on Monday, which should replace everything except Number Reasoning and Verbal Reasoning.

**Comment by alocher** [comment]
Sounds good, I'll just wait for the updated version then.

**Comment by Pete-York** [comment]
Ok I've neatened it up by combining the Multiple Choice image executables into a single executable called MultipleChoice.

I've also renamed Number Reasoning as Number Series, and added a small example stimulus csv file for each one.
[NumberSeries.zip](https://github.com/tatool/tatool-web/files/1736922/NumberSeries.zip)
[VerbalReasoning.zip](https://github.com/tatool/tatool-web/files/1736923/VerbalReasoning.zip)
[MultipleChoice.zip](https://github.com/tatool/tatool-web/files/1736924/MultipleChoice.zip)

**Comment by alocher** [comment]
That sounds perfect. I'll take a look and upload asap.

**Comment by Pete-York** [comment]
Great, thanks a bunch

**Comment by alocher** [comment]
@Pete-York: the Executables are now online and available in the tatool-share project. I made minor changes in order to follow the convention of other Executables.

1. Lowercase all Executable names.
2. Add prefix for all css classes to avoid any unwanted css class overrides.
3. Add graceful error message in case more iterations than stimuli are configured.
4. I'm not sure the verbalReasoning display works as expected though, give it a try and let me know if you want to change anything.

You can find the current version of all executables here:
https://github.com/tatool/tatool-web/tree/master/app/projects/public/tatool-share/executables

Also let me know if you want me to change the executable description being shown in the Editor.
