### ISSUE TITLE
"No data available" for export after completed sessions

### ISSUE THREAD

**Issue by Deiyo** [tatool/tatool-web#120]
When the sessions are initiated over the web link, there is "no data available" for download, even when sessions are marked as "completed" in the "Analytics" section and they have their session token assigned (confirming the completed session). 

I tried to select both "public" or "private" options in the module, but the data is never available for download if initiated over the link. The only two ways that data are available is if I initiate a module with either the "test" option inside of the "Editor" section or the "Start" option inside of the "Modules" section.  I already gathered quite some data, because I was convinced everything is in order - but is now the data lost?!?? Is it maybe available somewhere on the server? Please help.

**Comment by alocher** [comment]
Hi Deiyo,

I'm sorry to hear that you had issues with the uploads not appearing. I assume the problem is that you haven't checked the "Upload" checkbox in your Module General Setting. By default a Module only allows to "Download" your own local data and doesn't automatically upload to the Tatool Server, as to not spam the server with unnecessary data. 

So first of all, make sure you check "Upload" and republish your Module. Going forward, any sessions should automatically upload data once they're complete. You should also always test this before you go live with an experiment.

Now regarding your already gathered data, this can be simple or not so simple depending on your setup. First of all it's important to understand that Tatool always uploads any session/module specific data, but keeps trial data in a local database to the user. At the end of a session, Tatool checks if the "Upload" Exporter has been enabled, and if so, uploads the data to Analytics.

Now you said that you've used the URL to run your experiment, did you run this on a lab computer or did the users use their own computers? Did you use the extid parameter to identify your participants?

**Comment by alocher** [comment]
I sent you an email with the detailed instructions, as it requires a bit of work if not extids were used.
