### ISSUE TITLE
Response buttons not working on iPhone

### ISSUE THREAD

**Issue by taylorlmyers** [tatool/tatool-web#127]
Hi there,
It seems the response buttons on regular sized iPhones are too low, so it's necessary to scroll down to see them. However, the stimulus is now only partially visible and the response keys do not work. Is there some modification I can make to the module to decrease the distance between the stimulus and the response keys on mobile devices?

Thanks!

**Comment by alocher** [comment]
Sorry somehow missed this. Not all of our tasks/template functionality is as mobile friendly as we like. Do you mind telling me which task this is so I can get a better idea. I've got it on my plan to add some more responsiveness to some tasks when I get the time.

**Comment by taylorlmyers** [comment]
Hi Andre,

The Stroop task isn’t working on iPhones or iPads either in landscape or portrait.

Thanks for any help you can give!

Best,
Taylor

**Comment by alocher** [comment]
Unfortunately we don't have an IPhone for testing but I was able to do a quick online browser test and was able to see the issue you mentioned. This will most probably be due to the unresponsiveness of the status panel which will have to be rewritten. It seemed to work fine for me on an Ipad though.

I guess the only short term solution until we rewrite this would be to disable the status panels as that should allow you to fit stimulus and buttons on the screen on an iphone. Sorry I don't have any better news right now.

**Comment by alocher** [comment]
To be handled in separate task as part of rewrite of tasks.
