### ISSUE TITLE
Login window locks up in IE11

### ISSUE THREAD

**Issue by dgfitch** [tatool/tatool-web#27]
Hi guys! Nifty stuff.

I hate to be "that guy", but we were checking this tool out and I just had to be the jerk who opened it in Internet Explorer. On Win7 IE11.0.9600.17501, the login screen locks up. Sometimes right away, sometimes after I type a few characters.

I am accessing it here: http://www.tatool-web.com/#/login

I'll try it with a local install of the repo later.

**Comment by alocher** [comment]
Hi there and thanks for the feedback! Don't worry I'm not going to judge you on using IE :)

I do however have some issues replicating your problem. I've tested tatool-web with the exact same setup (Win 7 and IE11.0.9600.17501) and couldn't find any problems during the login. I'm just guessing here but could it be that the issue is related to some cached information regarding user/password as that's the only thing I can see happening on that screen where IE would behave differently. What exactly do you mean by locking up?

**Comment by dgfitch** [comment]
I don't actually use IE, I was just testing your cross-browser compatibility... :)

It's a full lockup: the window stops responding, IE asks if I want to reset the page; if I don't, IE eventually crashes. It was reliably repeating, but only on a particular machine in the lab, which may have weird IE settings. I'll investigate more next week and reopen if I find more details.
